services:
  database:
    image: mysql:latest # latest mysql image
    container_name: database # container name
    restart: unless-stopped # restart policy
    env_file: .env # adding env variables in the buold context
    environment: # add environment vars beyond .env
      - MYSQL_DATABASE=wordpress # set database name
    volumes:
      - dbdata:/var/lib/mysql # container directory
    command: '--default-authentication-plugin=caching_sha2_password' # override the default CMD for the image. Add option to docker which starts the MYSQL server on the container. Set auth mechanism
    networks: # set network
      - app-network

  wordpress:
    depends_on: # container starting after dependency container
      - database
    image: wordpress:6.5.2-fpm-alpine # set image to alpine with php-fpm processor to keep size down.
    container_name: wordpress # container name
    restart: unless-stopped # restart policy
    env_file: .env # set env file
    volumes:
      - wordpress:/var/www/html # set volume
    networks:
      - app-network # set ntwork

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.25.5-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    # -- webroot tells certbot to use the webroot plugin to place files in the webroot folder for authentication.
    # -- webroot-path: specifices the path of the webroot directory
    # -- email: preferred email for registrtion and recovery
    # -- agree-tos: agree to TOS
    # -- no-eff-email: no electronic frontier foundation  sharing of email
    command: certonly --webroot --webroot-path=/var/www/html --email admin@retronexus.net --agree-tos --no-eff-email --force-renewal -d www.retronexus.net -d retronexus.net

volumes:
  dbdata:
  wordpress:
  certbot-etc:

networks:
  app-network:
    driver: bridge
