services:
  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=caching_sha2_password'
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
