services:
  database:
    image: mysql:latest # latest mysql image
    container_name: database # container name
    restart: unless-stopped # restart policy
    env_file: .env # adding env variables in the buold context
    environment: # add environment vars beyond .env
      - MYSQL_DATABASE=wordpress # set database name
    volumes:
      - dbdata:/var/lib/mysql # container directory
    command: '--default-authentication-plugin=caching_sha2_password' # override the default CMD for the image. Add option to docker which starts the MYSQL server on the container. Set auth mechanism
    networks: # set network
      - app-network

  wordpress:
    depends_on: # container starting after dependency container
      - database
    image: wordpress:6.5.2-fpm-alpine # set image to alpine with php-fpm processor to keep size down.
    container_name: wordpress # container name
    restart: unless-stopped # restart policy
    env_file: .env # set env file
    volumes:
      - wordpress:/var/www/html # set volume
    networks:
      - app-network # set ntwork

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.25.5-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  dbdata:
  wordpress:

networks:
  app-network:
    driver: bridge
